[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/valorant-meta"
  to = "/projects/valorant-meta.html"
  status = 200

[[redirects]]
  from = "/vct-2026"
  to = "/projects/vct-2026.html"
  status = 200
